name: CI - Build & Tests
 
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests pytest (sans MySQL)
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
 
      - name: Installer Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 

      - name: Installer les dépendances
        run: pip install -r app/requirements.txt
 
      - name: Lancer les tests pytest
        run: pytest app/tests/ -v
  
  build:
    name: Vérifier que Docker build sans erreur
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
  
        # On build uniquement l'image Flask pour vérifier que le Dockerfile est valide
      - name: Build de l'image Docker Flask
        run: docker build ./app -t gymtrack-app:ci